#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.




menuentry "Ultramarine 43 ISO / Xfce" --class fedora {
	set iso_file="/opt/iso/ultramarine/latest/ultramarine-xfce.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	#set boot_option=""
	#set boot_option="quiet splash"
	set boot_option="root=live:CDLABEL=UM-Xfce-Live-Anaconda rd.live.image enforcing=0 rhgb"
	linux (loop)/boot/vmlinuz iso-scan/filename=$iso_file $boot_option
	initrd (loop)/boot/initramfs.img
}




menuentry "Ultramarine 43 ISO / Kde Plasma" --class fedora {
	set iso_file="/opt/iso/ultramarine/latest/ultramarine-kde-plasma.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	#set boot_option=""
	#set boot_option="quiet splash"
	set boot_option="root=live:CDLABEL=UM-Kd-Live-Anaconda rd.live.image enforcing=0 rhgb"
	linux (loop)/boot/vmlinuz iso-scan/filename=$iso_file $boot_option
	initrd (loop)/boot/initramfs.img
}




menuentry "Ultramarine 43 ISO / Budgie" --class fedora {
	set iso_file="/opt/iso/ultramarine/latest/ultramarine-budgie.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	#set boot_option=""
	#set boot_option="quiet splash"
	set boot_option="root=live:CDLABEL=UM-Budgie-Live-Anaconda rd.live.image enforcing=0 rhgb"
	linux (loop)/boot/vmlinuz iso-scan/filename=$iso_file $boot_option
	initrd (loop)/boot/initramfs.img
}




menuentry "Ultramarine 43 ISO / Gnome Shell" --class fedora {
	set iso_file="/opt/iso/ultramarine/latest/ultramarine-gnome-shell.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	#set boot_option=""
	#set boot_option="quiet splash"
	set boot_option="root=live:CDLABEL=UM-Gn-Live-Anaconda rd.live.image enforcing=0 rhgb"
	linux (loop)/boot/vmlinuz iso-scan/filename=$iso_file $boot_option
	initrd (loop)/boot/initramfs.img
}
