#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.








menuentry "Ultramarine 40 ISO / Flagship" --class Fedora {
	set iso_file="/opt/iso/ultramarine/latest/ultramarine-flagship-40-live-x86_64.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	#set boot_option=""
	#set boot_option="quiet splash"
	set boot_option="root=live:CDLABEL=UM-Flagship-Live rd.live.image enforcing=0 rhgb"
	linux (loop)/boot/vmlinuz-6.8.10-300.fc40.x86_64 iso-scan/filename=$iso_file $boot_option
	initrd (loop)/boot/initramfs-6.8.10-300.fc40.x86_64.img
}




menuentry "Ultramarine 40 ISO / Xfce" --class Fedora {
	set iso_file="/opt/iso/ultramarine/latest/ultramarine-xfce-40-live-x86_64.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	#set boot_option=""
	#set boot_option="quiet splash"
	set boot_option="root=live:CDLABEL=UM-Xfce-Live rd.live.image enforcing=0 rhgb"
	linux (loop)/boot/vmlinuz-6.8.10-300.fc40.x86_64 iso-scan/filename=$iso_file $boot_option
	initrd (loop)/boot/initramfs-6.8.10-300.fc40.x86_64.img
}




menuentry "Ultramarine 40 ISO / Kde Plasma" --class Fedora {
	set iso_file="/opt/iso/ultramarine/latest/ultramarine-kde-40-live-x86_64.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	#set boot_option=""
	#set boot_option="quiet splash"
	set boot_option="root=live:CDLABEL=UM-Kd-Live rd.live.image enforcing=0 rhgb"
	linux (loop)/boot/vmlinuz-6.8.10-300.fc40.x86_64 iso-scan/filename=$iso_file $boot_option
	initrd (loop)/boot/initramfs-6.8.10-300.fc40.x86_64.img
}




menuentry "Ultramarine 40 ISO / Gnome Shell" --class Fedora {
	set iso_file="/opt/iso/ultramarine/latest/ultramarine-gnome-40-live-x86_64.iso"
	search --set=iso_partition --no-floppy --file $iso_file
	probe --set=iso_partition_uuid --fs-uuid $iso_partition
	set img_dev="/dev/disk/by-uuid/$iso_partition_uuid"
	loopback loop ($iso_partition)$iso_file
	#set boot_option=""
	#set boot_option="quiet splash"
	set boot_option="root=live:CDLABEL=UM-Gn-Live rd.live.image enforcing=0 rhgb"
	linux (loop)/boot/vmlinuz-6.8.10-300.fc40.x86_64 iso-scan/filename=$iso_file $boot_option
	initrd (loop)/boot/initramfs-6.8.10-300.fc40.x86_64.img
}
